name: Deploy Api

on: workflow_dispatch
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: (cd api && yarn)

      - name: Build
        run: (cd api && yarn build)

      - name: Zip
        run: (cd api/build && zip -r ../function.zip .)

      - name: Deploy to AWS
        uses: appleboy/lambda-action@v0.1.9
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: geDOTorg-api
          zip_file: api/function.zip