name: Deploy Api

on: workflow_dispatch
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: (cd api && yarn)

      - name: Build
        run: (cd api && yarn build)

      - name: Move node_modules to dist
        run: (cd api && mv node_modules build/node_modules)

      - name: Zip
        run: (cd api/build && zip -r ../function.zip .)

      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: geDOTorg-api
          zip_file: api/function.zip